import type { ClimbingGym } from './types/types';

export const MOCK_GYMS: ClimbingGym[] = [
	{
		id: 1,
		name: 'Basecamp Bloor',
		city: 'Toronto',
		address: '677 Bloor St W, Toronto, ON M6G 1L3',
		mapUrl: 'https://maps.google.com/?q=Basecamp+Bloor',
		placeId: 'ChIJ-9999999999',
		coordinates: { latitude: 43.6644, longitude: -79.4132 },
		publicTransport: {
			subway: { line: 'Line 2', station: 'Christie' },
			busOrTram: true,
		},
		websiteUrl: 'https://basecampclimbing.ca',
		price: {
			currency: 'CAD',
			amount: 25,
			tax: '0.13',
			sourceUrl: 'https://basecampclimbing.ca/pricing',
		},
		iconUrl: 'gym-icon/basecamp.svg',
		imageUrl: 'gym-preview/basecamp-bloor-west.webp',
		area: { unit: 'sq ft', value: 7000 },
		climbingTypes: {
			boulder: true,
			autoBelay: true,
			topRope: true,
			lead: true,
		},
		boards: {
			moonBoard: true,
			kilterBoard: false,
			tensionBoard: false,
		},
	},
	{
		id: 2,
		name: 'Joe Rockheads',
		city: 'Toronto',
		address: '29 Fraser Ave, Toronto, ON M6K 1Y7',
		mapUrl: 'https://maps.google.com/?q=Joe+Rockheads',
		placeId: 'ChIJ-8888888888',
		coordinates: { latitude: 43.6391, longitude: -79.4239 },
		publicTransport: {
			subway: undefined,
			busOrTram: true,
		},
		websiteUrl: 'https://joerockheads.com',
		price: {
			currency: 'CAD',
			amount: 28,
			tax: '0.13',
			sourceUrl: 'https://joerockheads.com/rates',
		},
		iconUrl: 'gym-icon/joe-rockheads.jpg',
		imageUrl: 'gym-preview/joe-rockheads.webp',
		area: { unit: 'sq ft', value: 10000 },
		climbingTypes: {
			boulder: true,
			autoBelay: false,
			topRope: true,
			lead: true,
		},
		boards: {
			moonBoard: false,
			kilterBoard: true,
			tensionBoard: false,
		},
	},
	{
		id: 3,
		name: 'Boulderz Etobicoke',
		city: 'Etobicoke',
		address: '80 The East Mall, Etobicoke, ON M8Z 5X1',
		mapUrl: 'https://maps.google.com/?q=Boulderz+Etobicoke',
		placeId: 'ChIJ-7777777777',
		coordinates: { latitude: 43.6192, longitude: -79.5372 },
		publicTransport: {
			subway: undefined,
			busOrTram: true,
		},
		websiteUrl: 'https://boulderzclimbing.com',
		price: {
			currency: 'CAD',
			amount: 22,
			tax: '0.13',
			sourceUrl: 'https://boulderzclimbing.com/rates',
		},
		iconUrl: 'gym-icon/boulderz-climbing.png',
		imageUrl: 'gym-preview/boulderz-climbing-etobicoke.webp',
		area: { unit: 'sq ft', value: 8000 },
		climbingTypes: {
			boulder: true,
			autoBelay: true,
			topRope: true,
			lead: false,
		},
		boards: {
			moonBoard: true,
			kilterBoard: false,
			tensionBoard: false,
		},
	},
];
